In [5]:
#forbenius norms 
import tensorflow as tf
x_tf = tf.Variable([[1,2],[3,2]])
tf.norm(x_tf)

InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double, complex64, complex128
	; NodeDef: {{node Sqrt}}; Op<name=Sqrt; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE, DT_COMPLEX64, DT_COMPLEX128]> [Op:Sqrt]

In [3]:
import numpy as np 
x =np.array([[1,2],[3,4]])
np.linalg.norm(x)

5.477225575051661

In [11]:
#matrix multiplication
a = np.array([[3,4],[5,6],[7,8]])
b=np.array([1,2])
np.dot(a,b)


array([11, 17, 23])

In [16]:
#matrix multiplication using tensor flow

a = tf.Variable([[3,4],[5,6],[7,8]])
b=tf.Variable([1,2])
tf.linalg.matvec(a,b)


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23])>

In [28]:
a = tf.Variable([[3,4],[5,6],[7,8]])
b=tf.Variable([[1,9],[2,0]])
tf.linalg.matvec(a,b)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[39, 59, 79],
       [ 6, 10, 14]])>

In [33]:
#symmetrical matrix
import numpy as np
a = np.array([
    [0,1,2],
    [1,7,8],
    [2,8,9]
])
a.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [35]:
#identity matrix
import tensorflow as tf
x = tf.Variable([
    [1,0,0],
    [0,1,0],
    [0,0,1]
])
y=tf.Variable([25,2,5])
tf.linalg.matvec(x,y)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([25,  2,  5])>

In [11]:
#inberse of matrix
import numpy as np
x=np.array([[4,2],[-5,-3]])
x_in = np.linalg.inv(x)
y = np.array([4,-7])
np.dot(x_in,y)

array([-1.,  4.])

In [15]:
# import tensorflow as tf
# tf.linalg.inv(tf.Variable([[4,2],[-5,-3]]))
x = np.array([[-4,1],[-8,2]])
x


array([[-4,  1],
       [-8,  2]])